server:
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service
